second step
Alex-zzzz/books pull request #2
Opened 2023-10-24 14:22 UTC by Alex-zzzz

2023-10-24 17:04 UTC, Ivan95kos requested changes
please, fix all checks
<img width="862" alt="Знімок екрана 2023-10-24 о 18 53 35" src="https://github.com/Alex-zzzz/books/assets/41166578/6bfdde0f-4712-4242-94e1-5bf18d0bd507">

2023-10-25 10:02 UTC, kozhukhovsky approved these changes

2023-10-25 10:02 UTC, kozhukhovsky commented on .github/workflows/ci.yml
> +
```suggestion
```

2023-10-25 10:02 UTC, kozhukhovsky commented on src/main/java/online/book/store/dto/BookDto.java
> +
```suggestion
```

2023-10-25 10:02 UTC, kozhukhovsky commented on src/main/java/online/book/store/mapper/BookMapperImpl.java
> +    private BookDto dto = new BookDto();
why is not local?

2023-10-25 10:30 UTC, merged