first version of exercise 3
Alex-zzzz/books pull request #4
Opened 2023-10-27 08:34 UTC by Alex-zzzz

2023-10-27 10:58 UTC, kozhukhovsky requested changes

2023-10-27 10:58 UTC, kozhukhovsky commented on src/main/java/online/book/store/controller/BookController.java
> +        try {
In my opinion try/catch in controller is bad practice

2023-10-27 10:58 UTC, kozhukhovsky commented on src/main/java/online/book/store/service/BookService.java
> +    Optional<Book> getBookById(Long id);
```suggestion
    Book getBookById(Long id);
```

2023-10-27 10:58 UTC, kozhukhovsky commented on src/main/java/online/book/store/service/impl/BookServiceImpl.java
> +        return bookRepository.findById(id);
not return optional from service

2023-10-27 10:58 UTC, kozhukhovsky commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2023-10-27 15:02 UTC, okuzan requested changes

2023-10-27 15:02 UTC, okuzan commented on src/main/java/online/book/store/service/impl/BookServiceImpl.java
> +        return bookRepository.findById(id).orElseThrow();
Default exception message is uninformative, customize it, include id

2023-10-27 15:02 UTC, okuzan commented on src/main/java/online/book/store/controller/BookController.java
> +    public Book updateBookById(@PathVariable Long id, @RequestBody Book book) {
Pass dto here too

2023-10-27 15:02 UTC, okuzan commented on src/main/java/online/book/store/service/impl/BookServiceImpl.java
> +        return bookToUpdate;
use dto-entity mapper instead of setters

2023-10-28 09:19 UTC, olekskov approved these changes

2023-10-28 09:19 UTC, olekskov commented on src/main/java/online/book/store/service/impl/BookServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Can`t found entity by id: " + id));
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Can`t find book by id: " + id));
```

2023-10-28 09:37 UTC, merged